name: H2DB-CI-with-Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  Message: Shubham

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        # run: mvn clean package
        run: mvn clean install

      - name: List Contents of Target Directory
        run: ls -R target

      - name: Upload H2 Jar Artifact
        uses: actions/upload-artifact@v2
        with:
          name: h2-artifact
          path: target/*.war

      - name: Replace Placeholder in application.properties
        run: echo "MESSAGE:$MESSAGE"
        
